### PR TITLE
:bug: Fix appliedSpecHashAnnotation set if PreflightCheckPassed is not True

### LINKED ISSUE #755: [bug] InfrastructureProvider waiting for core provider even though CoreProvider is ready
**What steps did you take and what happened:**

In the following "aws" `InfrastructureProvider`, its PreflightCheckPasses has "False" status:
```sh
➜  ~ kubectl -n kcm-system get infrastructureproviders.operator.cluster.x-k8s.io aws -o yaml
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  annotations:
    meta.helm.sh/release-name: cluster-api-provider-aws
    meta.helm.sh/release-namespace: kcm-system
    operator.cluster.x-k8s.io/applied-spec-hash: c4b137728452224df6adb6b986e289a1ad71dccbd5b450abba0fcfe913c70d87
  creationTimestamp: "2025-03-18T12:03:28Z"
  finalizers:
  - provider.cluster.x-k8s.io
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: cluster-api-provider-aws
    helm.toolkit.fluxcd.io/namespace: kcm-system
  name: aws
  namespace: kcm-system
  resourceVersion: "4742"
  uid: 3f087388-7382-458a-9133-dce69dea90e3
spec:
  configSecret:
    name: aws-variables
    namespace: kcm-system
  manager:
    featureGates:
      ExternalResourceGC: true
    health: {}
    metrics: {}
    verbosity: 1
    webhook: {}
  version: v2.7.1
status:
  conditions:
  - lastTransitionTime: "2025-03-18T12:05:02Z"
    reason: MinimumReplicasAvailable
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-03-18T12:03:28Z"
    message: Waiting for the core provider to be installed.
    reason: WaitingForCoreProviderReady
    severity: Info
    status: "False"
    type: PreflightCheckPassed
  - lastTransitionTime: "2025-03-18T12:03:38Z"
    status: "True"
    type: ProviderInstalled
  contract: v1beta1
  installedVersion: v2.7.1
  observedGeneration: 1
```

The reason given for failing the pre flight checks is "Waiting for the core provider to be installed". So I take a look at the `CoreProvider` object but it shows everything is "Ready":

```sh
➜  ~ kubectl -n kcm-system get coreproviders.operator.cluster.x-k8s.io cluster-api -o yaml
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  annotations:
    meta.helm.sh/release-name: capi
    meta.helm.sh/release-namespace: kcm-system
    operator.cluster.x-k8s.io/applied-spec-hash: b4c63ea41e3a3fe6d7d7f1a92773f032dd2ce7e5f3e159a1ec09e7ae45d567a4
  creationTimestamp: "2025-03-18T12:03:18Z"
  finalizers:
  - provider.cluster.x-k8s.io
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: capi
    helm.toolkit.fluxcd.io/namespace: kcm-system
  name: cluster-api
  namespace: kcm-system
  resourceVersion: "3249"
  uid: 4ce1c558-5578-4b84-bf37-e1c34b5df5fe
spec:
  version: v1.9.5
status:
  conditions:
  - lastTransitionTime: "2025-03-18T12:03:48Z"
    reason: MinimumReplicasAvailable
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-03-18T12:03:18Z"
    status: "True"
    type: PreflightCheckPassed
  - lastTransitionTime: "2025-03-18T12:03:24Z"
    status: "True"
    type: ProviderInstalled
  contract: v1beta1
  installedVersion: v1.9.5
  observedGeneration: 1
```

So for some reason, the cluster-api-operator is not updating the status for aws `InfrastructureProvider` even though the "cluster-api" `CoreProvider` is Ready.

**What did you expect to happen:**

The expected behavior is that the `PreflightCheckPassed` condition should be "True" for all `InfrastructureProviders` because the "cluster-api" `CoreProvider` is Ready according to [this section of the preflightChecks](https://github.com/kubernetes-sigs/cluster-api-operator/blob/e2a065ee763a29c1b654e081204453aa4cfaac4e/internal/controller/preflight_checks.go#L177-L195) function.

**Anything else you would like to add:**

See more details in https://github.com/k0rdent/kcm/issues/1221, which also has a support bundle attached containing detailed logs.

**Environment:**

- Cluster-api-operator version: v0.17.1
- Cluster-api version:
- Minikube/KIND version: kind v0.23.0 go1.22.3 darwin/arm64
- Kubernetes version: (use `kubectl version`):
```sh
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.32.0
WARNING: version difference between client (1.30) and server (1.32) exceeds the supported minor version skew of +/-1
```
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by dmvolod**
**What this PR does / why we need it**:
Added fix and test for it, as this case (create not Ready CoreProvider before or after other providers) never been tested.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #755

### CODE REVIEW

File: internal/controller/genericprovider_controller.go [hunk 1]
```diff
@@ -206,7 +206,7 @@ func (r *GenericProviderReconciler) reconcile(ctx context.Context, provider gene
 
 		if !res.IsZero() || err != nil {
 			// the steps are sequential, so we must be complete before progressing.
-			return res, ignoreCoreProviderWaitError(err)
+			return res, err
```
Comment (furkatgofurov7) [inline internal/controller/genericprovider_controller.go:209]: so we are basically reverting the https://github.com/kubernetes-sigs/cluster-api-operator/pull/756/files#r2010321261?

File: internal/controller/genericprovider_controller.go [hunk 2]
```diff
@@ -164,7 +164,7 @@ func (r *GenericProviderReconciler) Reconcile(ctx context.Context, req reconcile
 
 	r.Provider.SetAnnotations(annotations)
 
-	return res, err
+	return res, ignoreCoreProviderWaitError(err)
```
Comment (furkatgofurov7) [inline internal/controller/genericprovider_controller.go:167]: can you elaborate on reasoning of this change?

File: internal/controller/genericprovider_controller.go (hunk 1 above)
Comment (dmvolod) [reply internal/controller/genericprovider_controller.go:209]: No, it's just code refactoring, not rerverting

File: internal/controller/genericprovider_controller.go (hunk 2 above)
Comment (furkatgofurov7) [reply internal/controller/genericprovider_controller.go:167]: Had another look and so we are ignoring `errCoreProviderWait` to ensure waiting for the core provider doesn’t cause unnecessary requeues and/or reconciliation and we will continue without treating this as an actual error?

Comment (dmvolod) [reply internal/controller/genericprovider_controller.go:167]: I've detected, that there are two places in controller Reconcile code with analyzing `if !res.IsZero() || err != nil {` result. One inside the `reconcile(..)` function and another one on top of it for calculating and validating spec changes hash. 

I set the error ignore to a higher level, but it should have been lowered. Also required test case was added.
