### PR TITLE
:bug: InfrastructureProvider waiting for core provider even though CoreProvider is ready

### LINKED ISSUE #755: [bug] InfrastructureProvider waiting for core provider even though CoreProvider is ready
**What steps did you take and what happened:**

In the following "aws" `InfrastructureProvider`, its PreflightCheckPasses has "False" status:
```sh
➜  ~ kubectl -n kcm-system get infrastructureproviders.operator.cluster.x-k8s.io aws -o yaml
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  annotations:
    meta.helm.sh/release-name: cluster-api-provider-aws
    meta.helm.sh/release-namespace: kcm-system
    operator.cluster.x-k8s.io/applied-spec-hash: c4b137728452224df6adb6b986e289a1ad71dccbd5b450abba0fcfe913c70d87
  creationTimestamp: "2025-03-18T12:03:28Z"
  finalizers:
  - provider.cluster.x-k8s.io
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: cluster-api-provider-aws
    helm.toolkit.fluxcd.io/namespace: kcm-system
  name: aws
  namespace: kcm-system
  resourceVersion: "4742"
  uid: 3f087388-7382-458a-9133-dce69dea90e3
spec:
  configSecret:
    name: aws-variables
    namespace: kcm-system
  manager:
    featureGates:
      ExternalResourceGC: true
    health: {}
    metrics: {}
    verbosity: 1
    webhook: {}
  version: v2.7.1
status:
  conditions:
  - lastTransitionTime: "2025-03-18T12:05:02Z"
    reason: MinimumReplicasAvailable
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-03-18T12:03:28Z"
    message: Waiting for the core provider to be installed.
    reason: WaitingForCoreProviderReady
    severity: Info
    status: "False"
    type: PreflightCheckPassed
  - lastTransitionTime: "2025-03-18T12:03:38Z"
    status: "True"
    type: ProviderInstalled
  contract: v1beta1
  installedVersion: v2.7.1
  observedGeneration: 1
```

The reason given for failing the pre flight checks is "Waiting for the core provider to be installed". So I take a look at the `CoreProvider` object but it shows everything is "Ready":

```sh
➜  ~ kubectl -n kcm-system get coreproviders.operator.cluster.x-k8s.io cluster-api -o yaml
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  annotations:
    meta.helm.sh/release-name: capi
    meta.helm.sh/release-namespace: kcm-system
    operator.cluster.x-k8s.io/applied-spec-hash: b4c63ea41e3a3fe6d7d7f1a92773f032dd2ce7e5f3e159a1ec09e7ae45d567a4
  creationTimestamp: "2025-03-18T12:03:18Z"
  finalizers:
  - provider.cluster.x-k8s.io
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: capi
    helm.toolkit.fluxcd.io/namespace: kcm-system
  name: cluster-api
  namespace: kcm-system
  resourceVersion: "3249"
  uid: 4ce1c558-5578-4b84-bf37-e1c34b5df5fe
spec:
  version: v1.9.5
status:
  conditions:
  - lastTransitionTime: "2025-03-18T12:03:48Z"
    reason: MinimumReplicasAvailable
    status: "True"
    type: Ready
  - lastTransitionTime: "2025-03-18T12:03:18Z"
    status: "True"
    type: PreflightCheckPassed
  - lastTransitionTime: "2025-03-18T12:03:24Z"
    status: "True"
    type: ProviderInstalled
  contract: v1beta1
  installedVersion: v1.9.5
  observedGeneration: 1
```

So for some reason, the cluster-api-operator is not updating the status for aws `InfrastructureProvider` even though the "cluster-api" `CoreProvider` is Ready.

**What did you expect to happen:**

The expected behavior is that the `PreflightCheckPassed` condition should be "True" for all `InfrastructureProviders` because the "cluster-api" `CoreProvider` is Ready according to [this section of the preflightChecks](https://github.com/kubernetes-sigs/cluster-api-operator/blob/e2a065ee763a29c1b654e081204453aa4cfaac4e/internal/controller/preflight_checks.go#L177-L195) function.

**Anything else you would like to add:**

See more details in https://github.com/k0rdent/kcm/issues/1221, which also has a support bundle attached containing detailed logs.

**Environment:**

- Cluster-api-operator version: v0.17.1
- Cluster-api version:
- Minikube/KIND version: kind v0.23.0 go1.22.3 darwin/arm64
- Kubernetes version: (use `kubectl version`):
```sh
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.32.0
WARNING: version difference between client (1.30) and server (1.32) exceeds the supported minor version skew of +/-1
```
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api-operator/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by dmvolod**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #755

### CODE REVIEW

File: internal/controller/genericprovider_controller.go [hunk 1]
```diff
@@ -206,7 +206,7 @@ func (r *GenericProviderReconciler) reconcile(ctx context.Context, provider gene
 
 		if !res.IsZero() || err != nil {
 			// the steps are sequential, so we must be complete before progressing.
-			return res, err
+			return reconcile.Result{}, err
```
Comment (wahabmk) [inline internal/controller/genericprovider_controller.go:209]: If any of the phases being looped over returned a result with RequeueAfter, then that would be ignored with this change.

Comment (dmvolod) [reply internal/controller/genericprovider_controller.go:209]: Yes, I know.
This is specially for the catching secondary events from the CoreProvider, There wasn't problem with it.
The single phase which is looking for the repeated Requeue is `preflightChecks`. 
It seems to code should be refactored a bit, but not for now.

Comment (wahabmk) [reply internal/controller/genericprovider_controller.go:209]: What I wanted to highlight was that it should work as you intended even without this change because it will return the `res` that is returned from `preflightChecks` (or any other phase).

Comment (dmvolod) [reply internal/controller/genericprovider_controller.go:209]: Yes, agree.
But in this case, we will get an additional reconcile cycles  while waiting CoreProvider to be ready instead of just catching event from it.

**Review by furkatgofurov7 — APPROVED** [review]
Thanks for the PR @dmvolod!

/approve

cc @wahabmk for a final review

File: test/e2e/air_gapped_test.go [hunk 2]
```diff
@@ -34,7 +34,7 @@ import (
 	"sigs.k8s.io/yaml"
 )
 
-var _ = Describe("Install Controlplane, Core, Bootstrap Providers in an air-gapped environment", func() {
+var _ = Describe("Install Controlplane, Core, Bootstrap Providers in an air-gapped environment", Ordered, func() {
```
Comment (Danil-Grigorev) [inline test/e2e/air_gapped_test.go:37]:
```suggestion
var _ = Describe("Install Controlplane, Core, Bootstrap Providers in an air-gapped environment", func() {
```

What is the need for `Ordered` in here? These tests should be capable of running in parallel in any order, but if they need a prerequisite steps - please add it to the test case itself.

**Review by Danil-Grigorev — COMMENTED** [review]
One question about Ordered usage, otherwise lgtm

File: test/e2e/air_gapped_test.go (hunk 2 above)
Comment (dmvolod) [reply test/e2e/air_gapped_test.go:37]: Seems to tests are not designed to work independently. I fixed this bug and tests are failed without fixing order. I will try till make them independent or combine most of pipelines in the single It in next PR.

File: internal/controller/genericprovider_controller.go [hunk 3]
```diff
@@ -206,7 +206,7 @@ func (r *GenericProviderReconciler) reconcile(ctx context.Context, provider gene
 
 		if !res.IsZero() || err != nil {
 			// the steps are sequential, so we must be complete before progressing.
-			return res, err
+			return res, ignoreCoreProviderWaitError(err)
```
[the remark this answers is not in the document]
Comment (dmvolod) [reply internal/controller/genericprovider_controller.go:209]: Yes, exactly.
