### PR TITLE
🐛: fix unknown provider errors when using fetchConfigs

### LINKED ISSUE #570: Unable to upgrade providers when using custom fetchconfig
**What steps did you take and what happened:**

When trying to perform an upgrade of already deployed providers, configured for [airgapped environment](https://cluster-api-operator.sigs.k8s.io/03_topics/02_configuration/01_air-gapped-environtment#air-gapped-environment) (custom config map), I have the following error in each provider's controller logs:
```text
capi-providers-cluster-api-operator-7fc9485cd9-jmmdt manager 2024-07-23T17:52:29.626242023+02:00 E0723 15:52:29.626100       1 controller.go:329] "Reconciler error" err="failed to get configuration for the InfrastructureProvider with name infrastructure-azure. Please check the provider name and/or add configuration for new providers using the .clusterctl config file" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="caaph-system/addon-helm" namespace="caaph-system" name="addon-helm" reconcileID="5c096dda-b062-4d1b-9fbb-02ec7e27602f"
```

Here, controller AddonProvider seems to check configuration of an InfrastructureProvider, but I have same error for BootstrapProvider controller for example, and InfrastructureProvider is complaining about BootstrapProvider:
```text
capi-providers-cluster-api-operator-7fc9485cd9-jmmdt manager 2024-07-24T08:25:39.452452000+02:00 E0724 06:25:39.452326       1 controller.go:329] "Reconciler error" err="failed to get configuration for the BootstrapProvider with name bootstrap-kubeadm. Please check the provider name and/or add configuration for new providers using the .clusterctl config file" controller="infrastructureprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="InfrastructureProvider" InfrastructureProvider="capz-system/infrastructure-azure" namespace="capz-system" name="infrastructure-azure" reconcileID="6bbf901c-baf7-412d-83b2-d3d90f37f9b2"
```

If i delete current provider version and apply new one, this provider is deployed without error, so the fetchConfig seems to be ok.

**What did you expect to happen:**

Upgrade of providers should happens no matter what kind of configuration is used (custom fetchconfig or "github manifest").

**Anything else you would like to add:**

Here is a full log about a controller reconciliation showing that it detects that version has changed but fails to perform upgrade:
```text
capi-providers-cluster-api-operator-7fc9485cd9-jmmdt manager 2024-07-24T08:47:30.818619253+02:00 I0724 06:47:30.818454       1 genericprovider_controller.go:62] "Reconciling provider" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="caaph-system/addon-helm" namespace="caaph-system" name="addon-helm" reconcileID="485e07af-e97f-4314-bd52-1db42de41262"
capi-providers-cluster-api-operator-7fc9485cd9-jmmdt manager 2024-07-24T08:47:30.818842756+02:00 I0724 06:47:30.818731       1 preflight_checks.go:58] "Performing preflight checks" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="caaph-system/addon-helm" namespace="caaph-system" name="addon-helm" reconcileID="485e07af-e97f-4314-bd52-1db42de41262"
capi-providers-cluster-api-operator-7fc9485cd9-jmmdt manager 2024-07-24T08:47:30.819070959+02:00 I0724 06:47:30.819002       1 preflight_checks.go:199] "Preflight checks passed" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="caaph-system/addon-helm" namespace="caaph-system" name="addon-helm" reconcileID="485e07af-e97f-4314-bd52-1db42de41262"
capi-providers-cluster-api-operator-7fc9485cd9-jmmdt manager 2024-07-24T08:47:30.819305962+02:00 I0724 06:47:30.819217       1 phases.go:240] "No configuration secret was specified" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="caaph-system/addon-helm" namespace="caaph-system" name="addon-helm" reconcileID="485e07af-e97f-4314-bd52-1db42de41262"
capi-providers-cluster-api-operator-7fc9485cd9-jmmdt manager 2024-07-24T08:47:31.117517239+02:00 I0724 06:47:31.117378       1 phases.go:257] "Custom fetch configuration config map was provided" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="caaph-system/addon-helm" namespace="caaph-system" name="addon-helm" reconcileID="485e07af-e97f-4314-bd52-1db42de41262"
capi-providers-cluster-api-operator-7fc9485cd9-jmmdt manager 2024-07-24T08:47:31.119239063+02:00 I0724 06:47:31.119171       1 phases.go:161] "Loading provider" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="caaph-system/addon-helm" namespace="caaph-system" name="addon-helm" reconcileID="485e07af-e97f-4314-bd52-1db42de41262"
capi-providers-cluster-api-operator-7fc9485cd9-jmmdt manager 2024-07-24T08:47:31.122121203+02:00 I0724 06:47:31.122021       1 phases.go:420] "Fetching provider" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="caaph-system/addon-helm" namespace="caaph-system" name="addon-helm" reconcileID="485e07af-e97f-4314-bd52-1db42de41262"
capi-providers-cluster-api-operator-7fc9485cd9-jmmdt manager 2024-07-24T08:47:31.419996575+02:00 I0724 06:47:31.419866       1 phases.go:475] "Version changes detected, updating existing components" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="caaph-system/addon-helm" namespace="caaph-system" name="addon-helm" reconcileID="485e07af-e97f-4314-bd52-1db42de41262"
capi-providers-cluster-api-operator-7fc9485cd9-jmmdt manager 2024-07-24T08:47:31.627523882+02:00 E0724 06:47:31.627407       1 controller.go:329] "Reconciler error" err="failed to get configuration for the InfrastructureProvider with name infrastructure-azure. Please check the provider name and/or add configuration for new providers using the .clusterctl config file" controller="addonprovider" controllerGroup="operator.cluster.x-k8s.io" controllerKind="AddonProvider" AddonProvider="caaph-system/addon-helm" namespace="caaph-system" name="addon-helm" reconcileID="485e07af-e97f-4314-bd52-1db42de41262"
```

From my understanding issue come from the fact that known providers list remains the [default one](https://github.com/kubernetes-sigs/cluster-api/blob/a5898a2f63b8d3c556f192b76794b5b67900be5d/cmd/clusterctl/client/config/providers_client.go#L422). The current controller is only aware of it's own provider custom configuration (see [here](https://github.com/kubernetes-sigs/cluster-api-operator/blob/771e8a30d2a88369d87f0932b0c69a39ac14ec56/internal/controller/phases.go#L250)) where it should have all providers custom infos to be able to check them [here](https://github.com/kubernetes-sigs/cluster-api/blob/a5898a2f63b8d3c556f192b76794b5b67900be5d/cmd/clusterctl/client/config/providers_client.go#L465) in this [loop](https://github.com/kubernetes-sigs/cluster-api/blob/ef04465b2ba76214eea570e27e8146c96412e32a/cmd/clusterctl/client/cluster/upgrader.go#L288).

**Environment:**

- Cluster-api-operator version: 0.11.0
- Cluster-api version: 1.7.4
- Minikube/KIND version: N/A
- Kubernetes version: (use `kubectl version`): v1.28.7
- OS (e.g. from `/etc/os-release`): Ubuntu 22.04.4 LTS

/kind bug

### PR DESCRIPTION
**Pull request by w21froster**
**What this PR does / why we need it**:
When using `fetchConfig` in the [provider spec](https://cluster-api-operator.sigs.k8s.io/03_topics/02_configuration/05_provider-spec-configuration.html?highlight=fetchconfig#provider-spec) for multiple providers, the operator does not properly pass information about other "custom" providers to the [clusterctl configuration](https://cluster-api.sigs.k8s.io/clusterctl/configuration#provider-repositories). Currently, the operator passes repository information about the current provider only, and the default list from `clusterctl`. This causes `clusterctl` to fail it's lagging provider check, which is intended to keep providers within a valid version skew to avoid a broken cluster, and prevents upgrading providers when using `fetchConfig` in multiple places.

This PR adds information about other providers that are using `fetchConfig` to the MemoryReader, so that clusterctl can properly pass this check.

**Which issue(s) this PR fixes**:
Fixes #570

### CODE REVIEW

File: internal/controller/phases.go [hunk 1]
```diff
@@ -562,6 +572,65 @@ func getProvider(provider operatorv1.GenericProvider, defaultVersion string) clu
...
+
+	providerLists := []client.ObjectList{
+		&operatorv1.CoreProviderList{},
+		&operatorv1.BootstrapProviderList{},
+		&operatorv1.ControlPlaneProviderList{},
+		&operatorv1.InfrastructureProviderList{},
+		&operatorv1.AddonProviderList{},
+		&operatorv1.IPAMProviderList{},
+		&operatorv1.RuntimeExtensionProviderList{},
+	}
```
Comment (dmvolod) [inline internal/controller/phases.go:588]: The provider lists are already collected inside the `operatorv1.ProviderLists` slice. It would be nice to use it.

File: internal/controller/phases.go [hunk 2]
```diff
@@ -562,6 +572,65 @@ func getProvider(provider operatorv1.GenericProvider, defaultVersion string) clu
 	return *clusterctlProvider
 }
 
+func (p *phaseReconciler) getCustomProviders(ctx context.Context) ([]operatorv1.GenericProvider, error) {
```
Comment (dmvolod) [inline internal/controller/phases.go:575]: Also, please move this function to the `util` package. You will need to utilize `genericProviderList` for casting which is not exporting.

File: util/util.go [hunk 3]
```diff
@@ -70,6 +70,40 @@ func ClusterctlProviderType(genericProvider operatorv1.GenericProvider) clusterc
...
 }
 
+// GetCustomProviders retrieves all custom providers using `FetchConfig` that aren't the current provider name / type.
+func GetCustomProviders(ctx context.Context, cl ctrlclient.Client, currProvider genericprovider.GenericProvider) ([]operatorv1.GenericProvider, error) {
+	customProviders := []operatorv1.GenericProvider{}
+	currProviderName := currProvider.GetName()
+	currProviderType := currProvider.GetType()
+
+	for _, providerList := range operatorv1.ProviderLists {
+		providerList, ok := providerList.(ctrlclient.ObjectList)
```
Comment (w21froster) [inline util/util.go:80]: Had to do some casting here to get the controller client to be able to accept the list, wondering if there is a better way to do this since it has to cast again immediately after to be able to use GetItems()

Comment (dmvolod) [reply util/util.go:80]: Yes, you could probably cast to the `genericProviderList` interface once time, as it's contains both for *List and GetIntem() methods.

File: internal/controller/phases.go [hunk 4]
```diff
@@ -147,6 +147,18 @@ func (p *phaseReconciler) initializePhaseReconciler(ctx context.Context) (reconc
 		return reconcile.Result{}, err
 	}
 
+	// Get all providers using fetchConfig that aren't the current provider.
```
Comment (furkatgofurov7) [inline internal/controller/phases.go:150]:
```suggestion
	// Get all custom providers using fetchConfig that aren't the current provider.
```

**Review by furkatgofurov7 — APPROVED** [review]
/approve

**Comment by w21froster** [comment]
Hey folks, sorry for the bump, anything else needed from me on this PR to get the LGTM? I went ahead and rebased off main. Thank you 🙇

**Comment by furkatgofurov7** [comment]
This is a huge patch, however, it is due to manifests included and changes are inside the `test` folder anyways, so I am merging it. 

/lgtm

**Comment by furkatgofurov7** [comment]
Thanks @w21froster working on the fix, appreciated 🥇
